package wei.leetcode.learn.string;

import org.springframework.stereotype.Component;

/**
 * 1332 RemovePalindromicSubsequences.
 * <p>
 * Given a string s consisting only of letters 'a' and 'b'.
 * In a single step you can remove one palindromic <strong>subsequence</strong> from s.
 * <p>
 * Return the minimum number of steps to make the given string empty.
 * <p>
 * A string is a subsequence of a given string,
 * if it is generated by deleting some characters of a given string without changing its order.
 * <p>
 * A string is called palindrome if is one that reads the same backward as well as forward.
 * <p>
 * 2020/2/8 12:30 下午
 *
 * @author wei
 * @version 1.0.0
 **/
@Component
public class RemovePalindromicSubsequences {

    public int removePalindromeSub(String s) {
        if (s.isEmpty()) return 0;
        else if ( s.equals(new StringBuilder(s).reverse().toString()) ) return 1;
        else return 2;
    }

}
